
version: '3.8'

services:
  storage-node-1:
    build: ./src
    ports:
      - "5000:5000"
    networks:
      - storage-network

  storage-node-2:
    build: ./src
    ports:
      - "5001:5000"
    networks:
      - storage-network

  storage-node-3:
    build: ./src
    ports:
      - "5002:5000"
    networks:
      - storage-network

networks:
  storage-network:
    driver: bridge
